# Generated by Django 3.2.25 on 2025-03-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_cle',
            field=models.TextField(default=''),
        ),
    ]
