# Generated by Django 3.2.25 on 2025-03-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_message_encrypted_cle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='encrypted_cle',
            field=models.TextField(),
        ),
    ]
