# Generated by Django 5.1.6 on 2025-03-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_message_encrypted_cle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
