# Generated by Django 3.2.25 on 2025-03-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userkey_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hash_m',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='sig',
            field=models.TextField(default=''),
        ),
    ]
