# Generated by Django 3.2.25 on 2025-04-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20250313_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_file',
            field=models.TextField(default=''),
        ),
    ]
