# Generated by Django 3.2.25 on 2025-04-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_message_encrypted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='filename',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='filetype',
            field=models.TextField(default=''),
        ),
    ]
