# Generated by Django 3.2.25 on 2025-04-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20250408_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_cle_file',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='hash_f',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='sig_file',
            field=models.TextField(default=''),
        ),
    ]
