# Generated by Django 3.2.25 on 2025-04-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20250412_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='private_key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userkey',
            name='salt',
            field=models.TextField(default=''),
        ),
    ]
