# Generated by Django 5.1.6 on 2025-04-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_encryptedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedmessage',
            name='self_crypted',
            field=models.TextField(default=''),
        ),
    ]
