# Generated by Django 3.2.25 on 2025-04-18 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_encryptedmessage_self_crypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedmessage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_encrypted_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
