# Generated by Django 3.2.25 on 2025-04-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_encryptedmessage_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedmessage',
            name='sig',
            field=models.TextField(default=''),
        ),
    ]
