# Generated by Django 3.2.25 on 2025-04-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='encrypted_file',
            field=models.BinaryField(),
        ),
    ]
