# Generated by Django 3.2.25 on 2025-04-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_message_encrypted_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedmessage',
            name='encrypted_file',
            field=models.BinaryField(),
        ),
    ]
