# Generated by Django 3.2.25 on 2025-04-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_encryptedmessage_encrypted_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedmessage',
            name='encrypted_file',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_file',
            field=models.BinaryField(null=True),
        ),
    ]
